# Generated by Django 4.1.2 on 2022-11-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("SP", "Sport Wear"),
                    ("OW", "Out Wear"),
                    ("M", "Men"),
                    ("W", "Women"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("NA", "New Arrival"), ("BS", "Best Seller"), ("U", "Used")],
                max_length=2,
            ),
        ),
    ]
