# Generated by Django 4.1.2 on 2022-11-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_link",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
