# Generated by Django 4.1.2 on 2022-11-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_item_image_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("K", "Kits"),
                    ("BA", "Balls"),
                    ("A", "Accessories"),
                    ("F", "Footwear"),
                    ("BG", "Bags"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="item", name="image_link", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[
                    ("S", "Standard"),
                    ("NA", "New Arrival"),
                    ("BS", "Best Seller"),
                    ("U", "Used"),
                ],
                max_length=2,
            ),
        ),
    ]
