# Generated by Django 4.1.2 on 2022-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_item_category_alter_item_image_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="image_link", field=models.TextField(),
        ),
    ]
